# Tensor格式有哪些
- 0：scalar 通常就是一个数值
- 1：vector 通常指特征，例如词向量特征，某一维度特征等
- 2：matrix 一般计算的都是矩阵，通常是多维的
- 3: n-dimensional tensor 三维数据

In [2]:
import torch
from torch import tensor

## Scalar

In [3]:
x = tensor(42.)
x

tensor(42.)

In [4]:
x.dim()

0

In [5]:
2 * x

tensor(84.)

In [6]:
x.item()

42.0

## Vector

In [7]:
v = tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [8]:
v.dim()

1

In [9]:
v.size()

torch.Size([3])

## Matrix
- 一般计算的都是矩阵，通常都是多维的

In [11]:
M = tensor([[1., 2.], [3., 4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [12]:
M.matmul(M) # 矩阵乘法

tensor([[ 7., 10.],
        [15., 22.]])

In [13]:
tensor([1., 0.]).matmul(M)

tensor([1., 2.])

In [14]:
M * M

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [15]:
tensor([1., 2.]).matmul(M)

tensor([ 7., 10.])